Exception error message if misconfigured password authsource, instead of:
TypeError: get_class(): Argument #1 ($object) must be of type object, null given