Exception error message if misconfigured password authsource, instead of: (#79)
TypeError: get_class(): Argument #1 ($object) must be of type object, null given